server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "product_db"
      username: "product"
      password: "product"